# Generated by Django 2.1.5 on 2019-02-09 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('area_code', models.IntegerField(null=True)),
                ('phone_number', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.CharField(max_length=100)),
                ('details_of_service_request', models.CharField(max_length=200)),
                ('special_instructions', models.CharField(max_length=200)),
                ('is_deleted', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Done', 'done'), ('Pending', 'pending')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=30)),
                ('is_deleted', models.IntegerField(default=0)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.bookings')),
            ],
            options={
                'db_table': 'Services',
            },
        ),
    ]
