# Generated by Django 2.1.5 on 2019-02-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190209_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='details_of_service_request',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pickup_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='postal_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='special_instructions',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
