# Generated by Django 2.1.5 on 2019-02-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20190209_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('Done', 'done'), ('Pending', 'pending')], default='pending', max_length=20),
        ),
    ]
