# Generated by Django 2.1.5 on 2019-02-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20190215_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
